// MBTI 人格趣事和特点描述
export const MBTI_FACTS: Record<string, {
    traits: string[];
    facts: string[];
    funnyQuote: string;
    // 有趣版本新增字段
    superPowers: string[];      // 超能力
    weaknesses: string[];       // 致命弱点
    soulmates: string[];        // 灵魂伴侣类型
    nemesis: string[];          // 冤家类型
    celebrities: string[];      // 名人同款
    userManual: string[];       // 使用说明书
    dailyFails: string[];       // 日常翻车现场
}> = {
    INTJ: {
        traits: ['战略思考者', '独立自主', '追求效率'],
        facts: [
            '世界上只有2%的人是INTJ，是最稀有的人格之一',
            'INTJ经常被称为"建筑师"，因为他们喜欢构建完整的系统',
            '许多著名的科学家和发明家都是INTJ',
            'INTJ通常在30岁后才真正"开窍"社交',
        ],
        funnyQuote: '我不是冷漠，我只是在节省不必要的社交能量',
        superPowers: ['未来预判', '一眼看穿本质', '永远有Plan B'],
        weaknesses: ['被迫闲聊会死机', '完美主义发作', '情感表达404'],
        soulmates: ['ENFP', 'ENTP'],
        nemesis: ['ESFP', 'ESFJ'],
        celebrities: ['马斯克', '诸葛亮', '甘道夫'],
        userManual: ['不要突然social', '给TA独处时间', '逻辑说服>情感绑架'],
        dailyFails: ['想了100种方案结果一个没执行', '解释半天对方还是不懂', '又把天聊死了'],
    },
    INTP: {
        traits: ['逻辑分析', '好奇心强', '理论爱好者'],
        facts: [
            'INTP被称为"逻辑学家"，是天生的问题解决者',
            '爱因斯坦据说就是INTP人格',
            'INTP可以花几个小时研究一个有趣的问题',
            'INTP的内心独白比任何人都丰富',
        ],
        funnyQuote: '这个问题很有趣...等等，已经凌暨3点了？',
        superPowers: ['无限深挖', '漏洞检测器', '脑内小剧场'],
        weaknesses: ['拖延晚期患者', '现实世界连接失败', '说着说着跪了'],
        soulmates: ['ENTJ', 'ENFJ'],
        nemesis: ['ESFJ', 'ESTJ'],
        celebrities: ['爱因斯坦', '比尔盖茨', '牛顿'],
        userManual: ['让TA想清楚再说', '别催结论', '接受TA的奇怪爱好'],
        dailyFails: ['想到绝妙主意但懒得动', '说了“待会”然后忘了', '又在脑子里吵赢了一架'],
    },
    ENTJ: {
        traits: ['天生领导者', '决断力强', '目标导向'],
        facts: [
            'ENTJ被称为"指挥官"，天生具有领导气质',
            '许多CEO和企业家都是ENTJ人格',
            'ENTJ是最不怕冲突的人格类型之一',
            'ENTJ在压力下反而表现更好',
        ],
        funnyQuote: '效率！效率！这会议30分钟能结束吗？',
        superPowers: ['执行力爆棚', '气场压制', '战略规划师'],
        weaknesses: ['工作狂不可控', '无法容忍低效', '关心方式像批评'],
        soulmates: ['INTP', 'INFP'],
        nemesis: ['ISFP', 'INFP'],
        celebrities: ['拿破仑', '张雨绮', '孙正义'],
        userManual: ['直接说重点', '别跟 TA 绕弯子', '给 TA 挑战而不是服从'],
        dailyFails: ['又把建议说成了命令', '开会变成一个人的独角戏', '关心人的方式像在骂人'],
    },
    ENTP: {
        traits: ['创新思维', '善于辩论', '多才多艺'],
        facts: [
            'ENTP被称为"辩论家"，喜欢挑战传统观念',
            'ENTP经常同时进行多个项目',
            '他们是派对上最有趣的人，也是最难说服的人',
            'ENTP的脑子里永远有新点子在冒泡',
        ],
        funnyQuote: '我不是在抬杠，我是在进行苏格拉底式对话',
        superPowers: ['点子王', '舌战群雄', '举一反三'],
        weaknesses: ['三分钟热度', '把所有人都怀疑了', '嘴比脑快'],
        soulmates: ['INTJ', 'INFJ'],
        nemesis: ['ISFJ', 'ISTJ'],
        celebrities: ['钱学森', '朱德·洛', '铁人'],
        userManual: ['别跟 TA 较真', '让 TA 辩赢比让 TA 闭嘴简单', '享受 TA 的脑洞'],
        dailyFails: ['又开了个新坑', '辩着辩着忘了自己的观点', '话说太快拤不回来'],
    },
    INFJ: {
        traits: ['富有洞察力', '理想主义', '善解人意'],
        facts: [
            'INFJ是最稀有的人格类型，仅占人口的1-2%',
            'INFJ被称为"提倡者"，经常成为他人的精神导师',
            '许多作家和心理咨询师都是INFJ',
            'INFJ能感知到别人没说出口的情绪',
        ],
        funnyQuote: '我知道你在想什么...不，真的，我知道',
        superPowers: ['读心术', '共情爆表', '拯救世界的使命感'],
        weaknesses: ['想太多容易累', '完美主义绚架', '被误解就自我封闭'],
        soulmates: ['ENTP', 'ENFP'],
        nemesis: ['ESTP', 'ISTP'],
        celebrities: ['甘地', '尼采', '娘娘'],
        userManual: ['真诚最重要', '别强迫社交', '认可 TA 的使命感'],
        dailyFails: ['教别人做自己却做不到', '内心戏太多表情管理失败', '又觉得没人懂我'],
    },
    INFP: {
        traits: ['富有创意', '忠于价值观', '浪漫理想'],
        facts: [
            'INFP被称为"调停者"，是和平主义者',
            '许多诗人、艺术家都是INFP',
            'INFP的内心世界比外在表现丰富一万倍',
            'INFP可以为了坚持原则而放弃很多东西',
        ],
        funnyQuote: '我的白日梦里有完整的世界观设定',
        superPowers: ['情感共鸣高手', '创意源泉', '坚守原则'],
        weaknesses: ['现实连接不稳定', '批评会致命', '拖延绝缝'],
        soulmates: ['ENFJ', 'ENTJ'],
        nemesis: ['ESTJ', 'ENTJ'],
        celebrities: ['莫奈', '周杰伦', '小王子'],
        userManual: ['温柔对待', '别否定 TA 的感受', '给 TA 做梦的空间'],
        dailyFails: ['又在脑子里写完了一本小说', '现实和梦想差距让我emo', '想太多什么都没干'],
    },
    ENFJ: {
        traits: ['鼓舞人心', '善于沟通', '乐于助人'],
        facts: [
            'ENFJ被称为"主人公"，天生的人格魅力',
            '许多教育家和政治家都是ENFJ',
            'ENFJ能让每个人都感觉自己很特别',
            'ENFJ是最容易建立深度人际关系的类型',
        ],
        funnyQuote: '你开心我就开心！真的！我是认真的！',
        superPowers: ['人格魅力 MAX', '情绪魔法师', '团队凝聚力'],
        weaknesses: ['取悂别人到失去自我', '不会拒绝', '想太多容易累'],
        soulmates: ['INFP', 'INTP'],
        nemesis: ['ISTP', 'ESTP'],
        celebrities: ['奥巴马', '孔子', '何炳'],
        userManual: ['记得关心 TA', '别让 TA 一个人撕', '真心赞美 TA'],
        dailyFails: ['又答应了做不到的事', '别人不开心我比谁都紧张', '为什么我在操心别人的人生'],
    },
    ENFP: {
        traits: ['热情洋溢', '创意无限', '社交达人'],
        facts: [
            'ENFP被称为"竞选者"，充满感染力',
            'ENFP是最难专注于一件事的人格之一',
            '他们的朋友圈遍布各行各业',
            'ENFP可以在5分钟内和陌生人成为朋友',
        ],
        funnyQuote: '哇这个想法太棒了！等等，那个也很棒！还有这个！',
        superPowers: ['感染力满分', '万人迷', '点子永远不断'],
        weaknesses: ['ADHD 附体', '承诺太快收不回', '无法处理无聊'],
        soulmates: ['INTJ', 'INFJ'],
        nemesis: ['ISTJ', 'ESTJ'],
        celebrities: ['海贼路飞', '小红书博主', 'Robin Williams'],
        userManual: ['给 TA 自由', '别打断 TA 的热情', '跟上 TA 的节奏'],
        dailyFails: ['同时开了五个坑一个没填', '热情来得快去得也快', '又忘了约的什么'],
    },
    ISTJ: {
        traits: ['可靠负责', '注重传统', '实事求是'],
        facts: [
            'ISTJ被称为"物流师"，是最可靠的人格类型',
            'ISTJ占人口约11-14%，是最常见的类型之一',
            '他们是公司和组织的中坚力量',
            'ISTJ的承诺就是铁板钉钉',
        ],
        funnyQuote: '按计划来，不要给我惊喜，我不喜欢惊喜',
        superPowers: ['超级可靠', '记忆宫殿', '执行力满分'],
        weaknesses: ['变化=大敵', '活在过去', '差不多先生本人'],
        soulmates: ['ESFP', 'ESTP'],
        nemesis: ['ENFP', 'ENTP'],
        celebrities: ['巫山', '周总理', '贝糖阿姨'],
        userManual: ['提前说清楚计划', '别临时改主意', '让 TA 做完再说'],
        dailyFails: ['计划被打乱原地爆炸', '又在吐槽现在的年轻人', '说好的5点为什么5点01分才来'],
    },
    ISFJ: {
        traits: ['温暖贴心', '尽职尽责', '保护欲强'],
        facts: [
            'ISFJ被称为"守卫者"，占人口约13%',
            'ISFJ是最体贴他人感受的类型之一',
            '许多护士、教师都是ISFJ',
            'ISFJ会记住你说过的每一个小细节',
        ],
        funnyQuote: '你冷不冷？饿不饿？我这有零食...',
        superPowers: ['贴心小棉袄', '细节记忆大师', '默默奉献'],
        weaknesses: ['不会拒绝', '委屈自己成全别人', '改变恐惧症'],
        soulmates: ['ESTP', 'ESFP'],
        nemesis: ['ENTP', 'ENFP'],
        celebrities: ['母亲大人', '朱茵基', '灭火器群主'],
        userManual: ['记得感谢 TA', '别让 TA 一个人抗', '主动问问 TA 要不要'],
        dailyFails: ['又答应帮忙结果弪到崩溃', '想说不但怕伤害关系', '明明很累还在笑'],
    },
    ESTJ: {
        traits: ['组织能力强', '务实高效', '坚持原则'],
        facts: [
            'ESTJ被称为"总经理"，天生的管理者',
            'ESTJ是最讲究规则和秩序的类型',
            '他们在任何团队中都会自然成为组织者',
            'ESTJ说到做到，从不拖延',
        ],
        funnyQuote: '规则就是规则！没有例外！好吧，这次例外...',
        superPowers: ['组织能力 MAX', '规则守护者', '执行小霸王'],
        weaknesses: ['古板代言人', '不懂读空气', '只认死理'],
        soulmates: ['ISFP', 'ISTP'],
        nemesis: ['INFP', 'ENFP'],
        celebrities: ['巫山女婿', '张飞', '王健林'],
        userManual: ['尊重 TA 的规则', '用事实说话', '别跟 TA 讲感觉'],
        dailyFails: ['又想教别人做人', '为什么他们不带脑子', '计划被打乱就爆炸'],
    },
    ESFJ: {
        traits: ['热心肠', '社交能手', '重视和谐'],
        facts: [
            'ESFJ被称为"执政官"，是最爱照顾人的类型',
            'ESFJ占人口约12%，非常常见',
            '他们是聚会和活动的最佳组织者',
            'ESFJ能记住每个人的生日和喜好',
        ],
        funnyQuote: '大家都吃饱了吗？要不要加点什么？',
        superPowers: ['社交花蝶', '氛围组', '人情往来达人'],
        weaknesses: ['太在意别人看法', '叫不得别人不开心', '八卦体质'],
        soulmates: ['ISTP', 'ISFP'],
        nemesis: ['INTP', 'INTJ'],
        celebrities: ['谢娜', '蔡康永', '朋友圈活跃的那位'],
        userManual: ['给 TA 社交场合', '多多夸赞', '别跟 TA 冷战'],
        dailyFails: ['又在关心别人吃什么', '朋友不回微信怕是不是我哪里做错了', '又在组局结果没人来'],
    },
    ISTP: {
        traits: ['动手能力强', '冷静分析', '喜欢冒险'],
        facts: [
            'ISTP被称为"鉴赏家"，是天生的工匠',
            '许多工程师、技师都是ISTP',
            'ISTP喜欢拆东西然后再装回去',
            '他们在危机时刻最冷静',
        ],
        funnyQuote: '说明书？不需要，我看一眼就知道怎么装',
        superPowers: ['危机处理师', '拆卸大师', '超级冷静'],
        weaknesses: ['情绪? 什么情绪?', '承诺恐惧症', '无聊时就消失'],
        soulmates: ['ESFJ', 'ESTJ'],
        nemesis: ['ENFJ', 'INFJ'],
        celebrities: ['贝尔·吉罗斯', '德拉科', '老干部'],
        userManual: ['给 TA 空间', '别问太多感受', '让 TA 动手解决问题'],
        dailyFails: ['又拆了东西装不回去', '别人问感受我不知道说什么', '想独处被说冷漠'],
    },
    ISFP: {
        traits: ['艺术气质', '温和低调', '活在当下'],
        facts: [
            'ISFP被称为"探险家"，是最有艺术天赋的类型',
            '许多艺术家、音乐家都是ISFP',
            'ISFP外表安静，内心是一片艺术海洋',
            '他们最懂得欣赏生活中的小美好',
        ],
        funnyQuote: '我不是社恐，我只是在观察这个美丽的世界',
        superPowers: ['美学天赋', '活在当下', '温柔治愈'],
        weaknesses: ['冲突恐惧症', '规划? 不存在的', '容易被忽视'],
        soulmates: ['ESTJ', 'ESFJ'],
        nemesis: ['ENTJ', 'ENFJ'],
        celebrities: ['蔡依林', '拉维尼', 'Bob Dylan'],
        userManual: ['给 TA 创作空间', '别催别逼', '欣赏 TA 的作品'],
        dailyFails: ['想说的话咕回去了', '又被当隐形人', '明天的事明天再说'],
    },
    ESTP: {
        traits: ['行动派', '适应力强', '喜欢刺激'],
        facts: [
            'ESTP被称为"企业家"，是最敢冒险的类型',
            'ESTP是急救场景中最冷静的人',
            '他们相信"做了再说"而不是"说了再做"',
            'ESTP是最不怕犯错的类型',
        ],
        funnyQuote: '想那么多干嘛？先干了再说！',
        superPowers: ['即时反应', '冒险达人', '充满充沛'],
        weaknesses: ['三思而后行? 不存在', '很快无聊', '承诺是什么'],
        soulmates: ['ISFJ', 'ISTJ'],
        nemesis: ['INFJ', 'ENFJ'],
        celebrities: ['成龙', 'Trump', '王思聡'],
        userManual: ['跟上 TA 的节奏', '别讲大道理', '一起去冒险'],
        dailyFails: ['又充动了', '后果是什么后果', '怎么又惹麻烦了'],
    },
    ESFP: {
        traits: ['天生表演者', '乐观开朗', '享受生活'],
        facts: [
            'ESFP被称为"表演者"，天生就是焦点',
            'ESFP能让任何场合都变得有趣',
            '许多演员、主持人都是ESFP',
            '他们是最会享受当下的人格类型',
        ],
        funnyQuote: '人生苦短，不开心的事明天再说！',
        superPowers: ['氛围担当', '快乐制造机', '超强感染力'],
        weaknesses: ['计划? 随缘', '严肃=无聊', '金鱼记忆'],
        soulmates: ['ISTJ', 'ISFJ'],
        nemesis: ['INTJ', 'INTP'],
        celebrities: ['赵丽颖', 'Marilyn Monroe', '吴京'],
        userManual: ['让 TA 当主角', '别打击 TA 的热情', '一起玩就对了'],
        dailyFails: ['又忘了正事', '为什么钱花完了', '明天的事明天的我担心'],
    },
};

// 加载时的状态提示文案
export const LOADING_MESSAGES = [
    '正在捕捉你的灵魂碎片...',
    '正在调配专属色彩...',
    '正在绘制你的人格轮廓...',
    '让AI感受你的独特气质...',
    '正在注入创意能量...',
    '马上就好，艺术需要一点时间...',
];
